version: '3.8'

services:
  # 1. Service APP (PHP-FPM)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: always
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
      - redis

  # 2. Service NGINX
  nginx:
    image: nginx:1.28-alpine
    container_name: laravel-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  # 3. Service MYSQL
  mysql:
    image: mysql:8
    container_name: laravel-mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql

  # 4. Service REDIS
  redis:
    image: redis:7-alpine
    container_name: laravel-redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redisdata:/data

  # 6. Service QUEUE WORKERS
  queue_default:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-queue-default
    restart: always
    command: php artisan queue:work --queue=default --sleep=3 --tries=3
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
      - redis
      - app

  queue_documents:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-queue-documents
    restart: always
    command: php artisan queue:work --queue=documents --sleep=2 --tries=3
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
      - redis
      - app

  queue_emails:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-queue-emails
    restart: always
    command: php artisan queue:work --queue=emails --sleep=5 --tries=3
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
      - redis
      - app

volumes:
  dbdata:
  redisdata:
